### ISSUE TITLE
Login with Providers (Google/LinkedIn) does not work

### ISSUE THREAD

**Issue by lorepirri** [tupuio/tupuapp#130]
### Describe the bug

If one tries to login with one of either the two methods, the authentication fails.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/6698585/227010036-26191bff-79d6-412f-9ff4-e24781a19b5e.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/6698585/227010113-dd64420a-3581-4f7d-9a8d-fe20be854bf7.png">

**Comment by lorepirri** [comment]
@tsg do you know how to solve this?

**Comment by tsg** [comment]
I'll check on this, sorry for missing the ping.

**Comment by tsg** [comment]
This seems to work for me locally, I'll share the secrets over Slack.

**Comment by maranta1** [comment]
Closing the issue because the linkedin auth works with the updated secrets
