### ISSUE TITLE
Set up Vercel or Netlify or equivalent to get live previews and CI/CD

### ISSUE THREAD

**Issue by tsg** [tupuio/tupuapp#23]
Ideally we'd use Vercel, but it's pretty expensive due to their pricing per user. I want to look into using Netlify and if that's also expensive, we can set up something by ourselves.

> I didn't manage yet to get `NEXTAUTH_URL` to be set dynamically in next.config.js, not sure why. According to nextauthjs/next-auth#3176 it should have worked. In practice this means that we cannot use the PR previews, which is a bummer. I'll try later, or perhaps we need to switch to another alternative.

**Checklist**
- [x]  get `NEXTAUTH_URL` to be set dynamically in next.config.js

**Comment by lorepirri** [comment]
Netlify has this sponsorship for open source projects: https://www.netlify.com/open-source/

![image](https://user-images.githubusercontent.com/6698585/153511754-acbaac29-4259-4a4a-8188-a9865d86cef1.png)

**Comment by tsg** [comment]
Thanks, that's cool. I think the free plan might be enough as well.

**Comment by lorepirri** [comment]
this might be done
