### ISSUE TITLE
One Time & Long Term Mentorship Status

### ISSUE THREAD

**Issue by Rambazamba6** [tupuio/tupuapp#26]
On the Mentor Profile - the mentor should have 2 status:
 

- [x] One Time Mentorship

- [x] Long Term Mentorship 

The status can be: free , busy

<img width="432" alt="Mentor-Settings" src="https://user-images.githubusercontent.com/69192304/155991726-abef31eb-566a-479b-879c-0fcc11cb98f4.png">

**Comment by Rambazamba6** [comment]
@tsg @ClaraPapaya @sabine-mansour @lorepirri 
I know we've talked to have ‘Your Profile‘ page the same for Mentor and Mentee. But we have to have a place for:
Mentor Incognito
One Time Mentorship
Long Term Mentorship

Shall we introduce a different ‘Your Profile‘ for Mentor as in the wireframe above?
Or shall we introduce these extra fields to the page ‘Your Expertise‘
<img width="566" alt="Screenshot 2022-02-12 at 06 47 39" src="https://user-images.githubusercontent.com/69192304/153698829-54775701-15f1-4d01-844f-dd331477d1a3.png">

**Comment by lorepirri** [comment]
done `in` #44
