### ISSUE TITLE
Mentor: Applications page: Create page + content

### ISSUE THREAD

**Issue by Rambazamba6** [tupuio/tupuapp#27]
- [x] Populate the Applications page with the requests from mentees as in the wireframe
<img width="493" alt="Mentor-Applications" src="https://user-images.githubusercontent.com/69192304/155996637-1096d451-98de-4b9a-8327-0497a1fcba90.png">

**Comment by ClaraPapaya** [comment]
in RequestCard component:
- [ ] add drop-down selection for status
- [ ] add date of request

**Comment by ClaraPapaya** [comment]
Still needed:

- [ ] show mentorship status

- [ ] show other profile info of Mentee (language, seniority, etc.)

**Comment by ClaraPapaya** [comment]
- [ ] Contact button function sends email to Mentee (who requested)
- [ ] Date the request came in
- [ ] visualisation for expiration of request (e.g. 7 days)

**Comment by ClaraPapaya** [comment]
This was solved in issue #58 Mentor: contact mentee
