### ISSUE TITLE
RequestCard: short message, shrinks width

### ISSUE THREAD

**Issue by lorepirri** [tupuio/tupuapp#62]
### Describe the bug

In Requests page, if the text of the message request is not long enough, the content of the request card does not fill the whole card.

### To Reproduce

1. Create a Mentorship Request with a short text (or edit one in the xata db)
1. Go to Requests page

### Screenshots

<img width="602" alt="image" src="https://user-images.githubusercontent.com/6698585/180466285-e7933d61-5c54-4c0f-8636-ca08d4435c7a.png">

**Comment by VladBrok** [comment]
Hello, I would like to contribute on this

**Comment by parthmarfatia** [comment]
Hi, I take up this issue!

**Comment by parthmarfatia** [comment]
Kindly share with me the .env.local contents

**Comment by lorepirri** [comment]
Hi all!

Thanks for being this proactive! We are kind of not ready yet to open to external contributors as we are figuring out how to share a few things (private keys and accounts).

Of course it is an open source project and this will be done in the next weeks but we can't be this responsive in this period as most of us are on holiday!

We will be back to you soon!

Btw: out of curiousity, how did you find this issue and our repo?

**Comment by VladBrok** [comment]
@lorepirri I found this issue on this site: https://goodfirstissues.com/ using 'filter by programming language: javascript' :)

**Comment by lorepirri** [comment]
> @lorepirri I found this issue on this site: https://goodfirstissues.com/ using 'filter by programming language: javascript' :)

Ah cool! I was wondering how this got popular suddenly. Well, it means that we will need to organize sooner than expected external collaborators onboarding. It will take a while.

Thanks for the patience!
