### ISSUE TITLE
Switching Role does not switch page

### ISSUE THREAD

**Issue by lorepirri** [tupuio/tupuapp#66]
### Describe the bug

We can use the menu on the right to switch between Mentee and Mentor role.

When we are on a page that is exclusive for one of the two roles (e.g. `Preferences` for a Mentor), and we switch to the other role, the page stays there and it's confusing.

The `Preferences` page and other pages exist only for one of the two roles. When we switch role, and we are on one of these pages, the app should go `Home`.

### To Reproduce

1. Switch to Mentor role
1. Go to `Preferences` page
2. Switch to Mentee role

### Expected behavior

The app goes `Home`

### Actual behavior

The app stays on the wrong  `Preferences` page, even though it has no meaning for a mentee.

### Screenshots

![switch-to-role-go-home](https://user-images.githubusercontent.com/6698585/180490269-e7292c49-e882-4568-8aa8-c6e07e366b1e.gif)

**Comment by debjit20504** [comment]
Can I take this issue ?

**Comment by sammybammy52** [comment]
hello, i would like to help with this bug

**Comment by lorepirri** [comment]
Hi all!

Thanks for being this proactive! We are kind of not ready yet to open to external contributors as we are figuring out how to share a few things (private keys and accounts).

Of course it is an open source project and this will be done in the next weeks but we can't be this responsive in this period as most of us are on holiday!

We will be back to you soon!

Btw: out of curiousity, how did you find this issue and our repo?

**Comment by debjit20504** [comment]
> Hi all!
> 
> Thanks for being this proactive! We are kind of not ready yet to open to external contributors as we are figuring out how to share a few things (private keys and accounts).
> 
> Of course it is an open source project and this will be done in the next weeks but we can't be this responsive in this period as most of us are on holiday!
> 
> We will be back to you soon!
> 
> Btw: out of curiousity, how did you find this issue and our repo?

Np, I'll be very happy to help you guys. and about finding this issue I was searching for the label:"good first issue" in my issue search bar so from there, I got this :)

**Comment by sammybammy52** [comment]
> Hi all!
> 
> Thanks for being this proactive! We are kind of not ready yet to open to external contributors as we are figuring out how to share a few things (private keys and accounts).
> 
> Of course it is an open source project and this will be done in the next weeks but we can't be this responsive in this period as most of us are on holiday!
> 
> We will be back to you soon!
> 
> Btw: out of curiousity, how did you find this issue and our repo?

i actually found it through the site goodfirstissues.com. enjoy your holidays :smile:

**Comment by lorepirri** [comment]
thanks everybody for the feedback! We're are working on it!
