### ISSUE TITLE
Mentorships and Applications pages show "Unhandled Runtime Error" when the the data from Your Profile page is not filled

### ISSUE THREAD

**Issue by Rambazamba6** [tupuio/tupuapp#89]
### Describe the bug

If the data from **Your Profile** page is not completed or accidentally deleted the pages **Mentorships** and **Applications** are showing the error: **Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'data.records.length')**

<img width="628" alt="image" src="https://user-images.githubusercontent.com/69192304/183088238-b4d9f379-3a14-432b-8d12-390bcf31c1d9.png">

**Comment by lorepirri** [comment]
this was caused temporarely because the user `test` had the wrong email in the DB. Closed by e4aec8749f18592281fb96a2f84f695985d38478, see #57.
