### ISSUE TITLE
Mentorship requests: add Long/Short term option and creation date

### ISSUE THREAD

**Issue by lorepirri** [tupuio/tupuapp#92]
### Problem
We want to give the option to mentees to request long or short term mentorships.

Part of the application already has this, implemented. The profile of the mentor has two booleans to indicate their availability for long/short term.

The Request for mentorship does not. This is about when a Mentee is asking for a mentorship, therefore should be able to choose among long or short term.

There is no creation of the request date either, only last update date.

### Feature Description

Update the flow adding the booleans for long/short term, and creation date:
- **xata** in the `tupuapp/xata/schema.yaml`:
  - add one boolean column `longterm` for long/short term for `requests`, and `relationships` tables (similar to `users.mentor`)
  - add creation date `creationDate` for `requests`
- `RequestModal`: add either a [switch for long term](https://github.com/tupuio/tupuapp/blob/42a1232db928f1cdb9646ccda8164eaf0a1ae6ab/components/MentorPreferencesForm/editor.js#L74), or a group of two radio buttons for two options long or short term, and also send its boolean value to `request.js` on submit.
- `request.js` save the new incoming boolean value `longterm` to the new `request`'s column `longterm`, save creation date value in `creationDate`.
- `acceptMentorship.js` endpoint: `createRelationship`, and the send email notification function (see `TODO`) should handle also the `longterm` value.
- `rejectMentorship.js` endpoint: the send email notification function (see `TODO`) should handle also the `longterm` value.
- `cancelRequest.js` endpoint: the send email notification function (see `TODO`) should handle also the `longterm` value.

**Comment by raluka** [comment]
Depends on:
- [x] https://github.com/tupuio/tupuapp/pull/93
- [x]  https://github.com/tupuio/tupuapp/pull/91

**Comment by raluka** [comment]
<img width="476" alt="Screenshot 2022-10-15 at 16 45 01" src="https://user-images.githubusercontent.com/4012836/195992571-8ba19f2e-e22f-4a12-a572-496a29cedadc.png">

Regarding about the usage of switch components: Can both options be on or off in the same time? Can user have bothe long term and one time option selected at the same time?

**Comment by lorepirri** [comment]
> Regarding about the usage of switch components: Can both options be on or off in the same time? Can user have both long term and one time option selected at the same time?

Thanks for your first contribution!

Well, ideally we could have two different boolean values: one mentor could be up for both, only for long, or only for short. 

Alternatively, it could be an Enum with three different options.

The important thing is to update accordingly the whole flow after this.

The Xata schema has currently two booleans in the mentor preferences/settings:

https://github.com/tupuio/tupuapp/blob/cd9abf43ddf2642842c8d577a8163cf2690f7499/xata/schema.yaml#L38-L41

The request should have these two fields as well, when created (you can add the two columns in the `schema.yaml` file for the `requests` table).

In a followup ticket, the request, when accepted, should also get these two fields, and the `relationship` table should have accordingly two new columns with the values updated. I don't remember if the follow up ticket is already there, let me check.

**Comment by lorepirri** [comment]
> * xata (add boolean column, creation date)
> * `RequestModal` (add switch long/short, send it to `request.js`)
> * `request.js` save it to the request
> * `acceptMentorship.js` endpoint (`createRelationship`, `updateRequest`, and send email notification), update the `lastUpdateDate` field.
> * `rejectMentorship.js` endpoint (`updateRequest`, and send email notification), update the `lastUpdateDate` field.
> * `cancelRequest.js` endpoint (`updateRequest`, and send email notification)

the dependencies are resolved as the PR was merged, all good.

**Comment by lorepirri** [comment]
> We also have a question related to the boolean field `long/short term`. What is the expected design for the database? Should it be one column, `long_term: true` (and we assume that `short_term` is false), or should it be 2 columns, one for each?

I think we went for two columns. They can be both true at the same time. Off at the same time? Maybe not, otherwise there would be no mentorship option I guess.

**Comment by lorepirri** [comment]
@raluka I'm reviewing this ticket now. It was OK as it was before: only one boolean long/short. This is about when a Mentee is asking for a mentorship, therefore should choose among long or short term. Sorry about this. I was not on this since more than a month. I am updating again the ticket. If you already worked on it, it's ok. It does not hurt to give both options to the Mentee.

**Comment by lorepirri** [comment]
@raluka The ticket is updated.
NB. Usually I add the columns in the xata dashboard while developing, because the changes to the `tupuapp/xata/schema.yaml` as far as I remember will be actionated when merged to `main`.

**Comment by raluka** [comment]
Hi @lorepirri , thank you for taking the time to revisit the ticket, and update it accordingly.

**Comment by lorepirri** [comment]
one could add a single [switch for long term] in my opinion, as you wish
